import { useState } from "react";

export default function Recipes() {
  const [query,setQuery]=useState("");const [results,setResults]=useState(null);const [loading,setLoading]=useState(false);const [detail,setDetail]=useState(null);const [dLoading,setDLoading]=useState(false);
  const search=async()=>{if(!query.trim())return;setLoading(true);setDetail(null);try{const res=await fetch("https://api.anthropic.com/v1/messages",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({model:"claude-sonnet-4-6",max_tokens:1000,system:"Return ONLY a JSON array of 6 recipe objects: {title,cuisine,time,difficulty,description,emoji}. No markdown.",messages:[{role:"user",content:`Find recipes for: ${query}`}],tools:[{type:"web_search_20250305",name:"web_search"}]})});const data=await res.json();const text=data.content?.filter(c=>c.type==="text").map(c=>c.text).join("");const m=text.match(/\[[\s\S]*\]/);if(m)setResults(JSON.parse(m[0]))}catch{setResults([])}setLoading(false)};
  const getDetail=async(recipe)=>{setDLoading(true);try{const res=await fetch("https://api.anthropic.com/v1/messages",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({model:"claude-sonnet-4-6",max_tokens:1000,system:"Return ONLY JSON: {title,servings,prep_time,cook_time,ingredients:[],steps:[],nutrition:{cal,protein,carbs,fat}}. No markdown.",messages:[{role:"user",content:`Full recipe: ${recipe.title} (${recipe.cuisine})`}],tools:[{type:"web_search_20250305",name:"web_search"}]})});const data=await res.json();const text=data.content?.filter(c=>c.type==="text").map(c=>c.text).join("");const m=text.match(/\{[\s\S]*\}/);if(m)setDetail(JSON.parse(m[0]))}catch{setDetail({error:true})}setDLoading(false)};
  const dc={Easy:"#22d3ee",Medium:"#f59e0b",Hard:"#ef4444"};
  return (
    <div>
      <div style={{display:"flex",gap:10,marginBottom:20}}><input className="inp" placeholder="Search any recipe... (e.g. healthy breakfast, paneer tikka)" value={query} onChange={e=>setQuery(e.target.value)} onKeyDown={e=>e.key==="Enter"&&search()} style={{flex:1}}/><button className="bp" onClick={search} disabled={loading}>{loading?"Searching...":"Find Recipes"}</button></div>
      {!results&&!loading&&<div style={{textAlign:"center",padding:"50px 20px"}}><div style={{fontSize:56,marginBottom:16}}>🍳</div><h3 style={{color:"#fde8e0",fontWeight:700,fontSize:20,marginBottom:6,fontFamily:"Rajdhani,Inter,sans-serif"}}>Discover Recipes</h3><p style={{color:"#6b4a42",fontSize:14,marginBottom:24}}>Flame Oracle finds the best recipes from across the web</p><div style={{display:"flex",gap:8,justifyContent:"center",flexWrap:"wrap"}}>{["Healthy Breakfast","Quick Lunch","Indian Dinner","Protein Smoothie","Vegan Bowl","Keto Snacks"].map(s=><span key={s} className="chip chip-i" onClick={()=>setQuery(s)} style={{padding:"8px 16px"}}>{s}</span>)}</div></div>}
      {results&&!detail&&<div style={{display:"grid",gridTemplateColumns:"repeat(auto-fill,minmax(280px,1fr))",gap:14}}>{results.map((r,i)=><div key={i} className="gc" onClick={()=>getDetail(r)} style={{cursor:"pointer"}}><div style={{fontSize:40,marginBottom:10}}>{r.emoji}</div><div style={{fontWeight:700,fontSize:16,color:"#fde8e0",marginBottom:4}}>{r.title}</div><div style={{fontSize:13,color:"#6b4a42",marginBottom:12,lineHeight:1.5}}>{r.description}</div><div style={{display:"flex",gap:10,fontSize:12}}><span style={{padding:"4px 10px",borderRadius:100,background:"rgba(239,68,68,.08)",color:"#f87171"}}>⏱ {r.time}</span><span style={{padding:"4px 10px",borderRadius:100,background:`${dc[r.difficulty]||"#f59e0b"}12`,color:dc[r.difficulty]||"#f59e0b"}}>{r.difficulty}</span><span style={{padding:"4px 10px",borderRadius:100,background:"rgba(251,191,36,.08)",color:"#fbbf24"}}>{r.cuisine}</span></div></div>)}</div>}
      {dLoading&&<div style={{textAlign:"center",padding:50}}><div style={{fontSize:40,animation:"float 1.5s ease-in-out infinite"}}>🍳</div><p style={{color:"#6b4a42",marginTop:12}}>Loading recipe details...</p></div>}
      {detail&&!detail.error&&<div className="fade-in"><button className="bg" onClick={()=>setDetail(null)} style={{marginBottom:14}}>← Back to results</button><div className="gs"><h3 style={{fontSize:22,fontWeight:800,color:"#ef4444",marginBottom:6,fontFamily:"Rajdhani,Inter,sans-serif"}}>{detail.title}</h3><div style={{display:"flex",gap:16,fontSize:13,color:"#6b4a42",marginBottom:20,flexWrap:"wrap"}}><span>👥 {detail.servings} servings</span><span>⏱ Prep: {detail.prep_time}</span><span>🔥 Cook: {detail.cook_time}</span></div>{detail.nutrition&&<div style={{display:"flex",gap:10,marginBottom:20,flexWrap:"wrap"}}>{[["Cal",detail.nutrition.cal,"#ef4444"],["Protein",detail.nutrition.protein+"g","#f97316"],["Carbs",detail.nutrition.carbs+"g","#f59e0b"],["Fat",detail.nutrition.fat+"g","#fbbf24"]].map(([l,v,c])=><span key={l} style={{fontSize:12,padding:"6px 14px",borderRadius:100,background:`${c}10`,color:c,fontWeight:600,border:`1px solid ${c}20`}}>{l}: {v}</span>)}</div>}<div className="sl" style={{color:"#f97316"}}>Ingredients</div><div style={{marginBottom:20}}>{detail.ingredients?.map((ing,i)=><div key={i} style={{fontSize:14,padding:"8px 0",borderBottom:"1px solid rgba(239,68,68,.05)",display:"flex",alignItems:"center",gap:10}}><span style={{color:"#ef4444",fontSize:8}}>🔥</span>{ing}</div>)}</div><div className="sl" style={{color:"#f59e0b"}}>Instructions</div>{detail.steps?.map((step,i)=><div key={i} style={{fontSize:14,padding:"12px 0",borderBottom:"1px solid rgba(239,68,68,.05)",display:"flex",gap:14,lineHeight:1.6}}><span style={{width:28,height:28,borderRadius:8,flexShrink:0,background:"linear-gradient(135deg,rgba(239,68,68,.12),rgba(249,115,22,.08))",display:"flex",alignItems:"center",justifyContent:"center",color:"#f87171",fontSize:13,fontWeight:700}}>{i+1}</span><span style={{color:"#c8b0a8"}}>{step}</span></div>)}</div></div>}
    </div>
  );
}
